services:
  db:
    container_name: db
    image: postgres:17.5-alpine3.21
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: northwind
      POSTGRES_PASSWORD: northwind
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./initdb.d/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U northwind']
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  postgresql_data:
    driver: local
